micronaut:
  application:
    name: subscription-plan
  server:
    port: 8081
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
          allowedMethods:
            - GET
ec2-instance: i-0b2219c07e40e5389
ec2-region: eu-central-1a