micronaut:
  application:
    name: subscription-plan
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
          allowedMethods:
            - GET
ec2-instance: i-0594629d212aa0872
ec2-region: eu-central-1b