micronaut:
  application:
    name: subscription-plan
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
          allowedMethods:
            - GET
  ssl:
    enabled: true
    key-store:
      path: classpath:ec2-1.p12
      password: "{password}"
      type: PKCS12
